### ISSUE TITLE
Kubernetes Clone

### ISSUE THREAD

**Issue by MrHamel** [DtxdF/LittleJet#2]
I am a bit lost on this project and related dependencies, because this project largely reinvents Kubernetes, but with a VPN setup to tie multiple nodes together. I also do not see the use case where a load balancer in one location would have backends in different countries, it adds to the latency and creates a poor user experience.

**Comment by DtxdF** [comment]
It's not a Kubernetes clone in any sense, it wasn't even inspired by it. And deploying a website in several countries was just an example, you just have to think a bit to see how many other examples can be there. For LittleJet it is irrelevant if you deploy an application in Argentina or Canada, you can deploy your application in the same organization but with different servers for redundancy and load balancing purposes. Also note that the VPN configuration is entirely optional.

**Comment by DtxdF** [comment]
This issue has been closed due to inactivity. You can reopen it if you wish.
